feat(sb): misc improvements
kubelt/kubelt pull request #1045
Opened 2022-11-17 20:59 UTC by crimeminister

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Closes # (issue)
- Closes # (issue)
- Closes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires or is a documentation update
- Security Fix

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-17 21:00 UTC, crimeminister commented on platform/starbase/curl/kb_appAuthCheck.json
> +  "params": {
@szkl I'd appreciate it if you could help me populate this with example request data.

2022-11-17 23:10 UTC, crimeminister commented on packages/cores/application/index.ts
> +    if (app?.published == true) {
We can return an error from the worker if that's what you want the caller to get?

2022-11-17 23:12 UTC, crimeminister commented on packages/cores/application/schema.ts
> +      name: "public_profile",
I was actually thinking of reducing the name to just `profile` since it's a method on an application already, and this name is turned into a method on the constructed client, e.g. `app.appProfile()` vs. `app.publicAppProfile()` vs `app.profile()`. These names are never exposed outside of a worker, though, so it's more for our internal consumption and preference for naming scheme.

2022-11-17 23:16 UTC, crimeminister commented on packages/cores/user/index.ts
>  export class StarbaseUser {
That's what I'm planning to do, but it's not ready yet (given what we talked about re. storing edges in a DB, etc.) so this is mean to be a stopgap. The other concern is what to do with console-specific information about a user, e.g. if a user has "settings" for console (number of images to show in a page, etc.), I would default to putting it in this object to keep things encapsulated. Alternately, I could store that kind of data in a remote service e.g. StorageAPI, or would need a way to associate arbitrary info with a User core.

2022-11-18 12:44 UTC, szkl commented on packages/cores/application/index.ts
> +    if (app?.published == true) {
Do you mean HTTP 404 or an "not found" error as a JSON-RPC response?

2022-11-18 12:51 UTC, szkl requested changes

2022-11-18 12:51 UTC, szkl commented on platform/starbase/curl/kb_appAuthCheck.json
> +    "redirectURL": "https://console.kubelt.com/dashboard",
Shouldn't this be called `redirectUri` as it might not be a location depending on the application?

2022-11-18 12:51 UTC, szkl commented on platform/starbase/curl/kb_appAuthCheck.json
> +  "params": {
It looks good as it is. Just needs some scopes.

2022-11-18 12:51 UTC, szkl commented on platform/starbase/curl/kb_appAuthCheck.json
> +    "scopes": [],
```suggestion
    "scopes": ["app:admin"],
```

2022-11-18 12:51 UTC, szkl commented on platform/starbase/curl/kb_appAuthCheck.json
> +    "redirectURL": "https://console.kubelt.com/dashboard",
```suggestion
    "redirectUri": "https://console.kubelt.com/dashboard",
```

2022-11-18 15:30 UTC, crimeminister commented on packages/cores/application/schema.ts
> +      name: "public_profile",
`kb_appProfile` is meant to just return public profile information. The complete app record is available from `kb_appFetch`. And after our discussion yesterday I have added `kb_appAuthCheck` to perform a check as part of the auth flow.

2022-11-18 15:40 UTC, crimeminister commented on packages/cores/user/index.ts
>  export class StarbaseUser {
My immediate need is to store a list of user's apps so I can display those options in the console UI. Do you want that info in the storage API, accessed by service binding to oort?

I had planned to create the user object and others as well, e.g. a node for each smart contract belonging to an app (associated with links), and those apps linked to a local user node, and the local starbase user node linked to the canonical user core owned by oort that identifies each user uniquely. Should we be leaning into the graph architectural pattern, multiplying the number of nodes and edges we create, keeping nodes small (storing only locally useful data) and mediating access to the data via scopes, etc.?

2022-11-18 15:41 UTC, crimeminister commented on platform/starbase/curl/kb_appAuthCheck.json
> +    "redirectURL": "https://console.kubelt.com/dashboard",
I changed it to match what was already stored, and because I wasn't imagining a redirect to anything but a web app. Happy to change it to be `Uri` if you think that fits better?

2022-11-18 15:51 UTC, crimeminister commented on packages/cores/application/index.ts
> +    if (app?.published == true) {
> 

Where possible, I am trying to deal with exceptional conditions and errors in the workers to avoid complicating DOs, which I see mainly as simple state management and synchronization primitives.

2022-11-18 17:54 UTC, crimeminister commented on packages/cores/user/index.ts
>  export class StarbaseUser {
Sorted this out offline. Thanks for the feedback @maurerbot.

2022-11-18 17:56 UTC, crimeminister commented on platform/starbase/curl/kb_appAuthCheck.json
> +  "params": {
@szkl I committed your change adding an example scope. If it turns out we don't need that info as part of the auth flow, please let me know and I'll update the list of parameters for this call in the schema and avoid including scopes as part of the comparison check.

2022-11-18 18:37 UTC, szkl approved these changes

2022-11-18 18:38 UTC, merged