feat(galaxy): polygon nft lookup
kubelt/kubelt pull request #1141
Opened 2022-12-06 19:04 UTC by poolsar42

# Description

Adds support for any polygon alchemy client. Doesn't return anything for polygon right in this draft

- Closes #1118
- Closes # (issue)
- Closes # (issue)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-06 21:16 UTC, poolsar42 commented on packages/alchemy-client/index.ts
> +  mumbai = 'mumbai',
specified this in env vars but mumbai is polygon testnet
now added polygon mainnet/testnet, ethereum mainnet and goerli

2022-12-07 10:57 UTC, Cosmin-Parvulescu requested changes

2022-12-07 10:57 UTC, Cosmin-Parvulescu commented on platform/galaxy/src/env.ts
> +  ALCHEMY_GOERLI_KEY: string
I think we just need two env variables per chain: KEY NETWORK

```
# ETHEREUM
ALCHEMY_ETH_KEY
ALCHEMY_ETH_NETWORK

# POLYGON
ALCHEMY_POLYGON_KEY
ALCHEMY_POLYGON_NETWORK
```

There might also be a need for `ALCHEMY_ETH_CHAIN` ('eth') as well as `ALCHEMY_POLYGON_CHAIN` ('polygon?') but I think those are good candidates for code instantiation, maybe not environment variables.

2022-12-07 10:57 UTC, Cosmin-Parvulescu commented on platform/galaxy/src/env.ts
> +  'ALCHEMY_GOERLI_KEY',
Make sure to also update the .dev.vars.example` when adding / removing env variables.

2022-12-07 10:57 UTC, Cosmin-Parvulescu commented on platform/galaxy/src/schema/resolvers/nfts.ts
> +        let [alchemyRes, alchemyPolygonRes] = await Promise.all([
I think we need to first call the `getContractsForOwner` and get NFTs with a configurable count for each contract, thus changing the shape of the response to match the new designs in Figma. Then we would get something like:
```
{ 
  fooContract: {
    ...details,
    nfts: [
      // Configurable NFT count
      ...nfts
    ]
  },
  barContract: {
    ...details,
    nfts: [
      // Configurable NFT count
      ...nfts
    ]
  }
}
```

cc: @maurerbot

2022-12-07 17:48 UTC, poolsar42 commented on platform/galaxy/src/schema/resolvers/nfts.ts
> +
Updated

2022-12-09 20:50 UTC, crimeminister approved these changes

2022-12-09 20:53 UTC, crimeminister approved these changes

2022-12-09 21:18 UTC, Cosmin-Parvulescu approved these changes

2022-12-09 21:22 UTC, merged