feat(access): create edges to link sessions
kubelt/kubelt pull request #1330
Opened 2022-12-30 18:02 UTC by crimeminister

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Closes # (issue)
- Closes # (issue)
- Closes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires or is a documentation update
- Security Fix

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-09 21:38 UTC, crimeminister commented
@maurerbot In `@kubelt/platform.address` method `setAddress` we require an `X-3RN` header, but in the input parameters we require an explicit `address: AddressURN`. Can we remove one or the other?

2023-01-09 21:44 UTC, crimeminister commented
@maurerbot When calling `@kubelt/platform.address` method `setAccount` I am seeing the error:
```
addressNode.class.getAddress is not a function
```
Can you confirm this is happening for you also?

2023-01-10 18:53 UTC, crimeminister commented
> 

I was thinking here specifically of the `setAddress` method.

2023-01-10 19:00 UTC, crimeminister commented on platform/access/src/jsonrpc/middleware/validators.ts
> +
Moved!

2023-01-10 19:05 UTC, crimeminister commented on platform/account/src/jsonrpc/methods/getSessions.ts
> +// Consider moving to inputValidators if potentially reusable.
DRYed up!

2023-01-10 19:29 UTC, crimeminister commented on platform/access/src/jsonrpc/methods/exchangeToken.ts
> +    const edgesClient = createEdgesClient(ctx.Edges)
I borrowed this pattern from elsewhere in the codebase, did you want this updated everywhere it's happening?

2023-01-10 20:33 UTC, crimeminister commented on platform/access/src/jsonrpc/methods/revokeSession.ts
> +  if (account === undefined) {
Added `RequireAccount` middleware to enforce the requirement that an account be supplied. This still requires that we use `!` on the `ctx.accountURN` in the method handler though.

2023-01-10 21:37 UTC, crimeminister commented on platform/access/src/jsonrpc/methods/exchangeToken.ts
> +    const edgesClient = createEdgesClient(ctx.Edges)
Service client is now injected using `InjectEdges` middleware.

2023-01-10 21:37 UTC, crimeminister commented on platform/access/src/jsonrpc/methods/revokeSession.ts
>    const edgesClient = createEdgesClient(ctx.Edges)
Service client is now injected using InjectEdges middleware.

2023-01-10 22:54 UTC, crimeminister commented on platform/access/src/jsonrpc/methods/getSession.ts
> +  const accessNode = await initAccessNodeByName(name, ctx.Access)
Right now the access node URN is being provided as an input parameter in the `getSession` method and in the `revokeSession` method. Presumably if we initialize the access node client in a middleware we'd want to provide the URN as a header instead, the way the `X-3RN` is used to provide the `addressURN`  in the `address` service. Is that your preference, or does it make sense to pass along the `accessURN` value as an input parameter, and use a utility fn to construct the client?

2023-01-11 00:12 UTC, crimeminister commented on platform/access/src/jsonrpc/methods/getSession.ts
> +  const accessNode = await initAccessNodeByName(name, ctx.Access)
Cf. `InjectAccessNode` middleware.

2023-01-11 16:52 UTC, szkl requested changes
It is not JSON-RPC anymore. I think the request body snippets in `curl` directory are useless now.

2023-01-11 16:52 UTC, szkl commented on packages/platform-middleware/jwt.ts
> +  if (ctx?.accountURN === undefined) {
would miss `null` value

2023-01-11 16:52 UTC, szkl commented on platform/access/src/context.ts
> +  edgesClient?: ReturnType<typeof createEdgesClient>
Why optional? If this can be avoided then non-null assertion (!) would be unnecessary in the usage references.

2023-01-11 16:52 UTC, szkl commented on platform/access/src/jsonrpc/middleware/injectAccessNode.ts
> +      ...ctx,
The object spread operator usage should come before the overrides.

2023-01-11 16:52 UTC, szkl commented on platform/access/src/jsonrpc/middleware/injectAccessNode.ts
> +export const InjectAccessNode: BaseMiddlewareFunction<Context> = async ({
The other workers used a setter name pattern. E.g. `setAccessNode`.

2023-01-11 16:52 UTC, szkl commented on platform/access/src/nodes/access.ts
> +      expiry = new Date(expiryTime).toUTCString()
Wouldn't it be better to have a UNIX timestamp instead?

2023-01-11 16:52 UTC, szkl commented on platform/access/src/nodes/access.ts
> +  if (creationTime === undefined) {
Strict equality (===) would miss `null` value, also any other empty value of other types.

Usually `!creationTime` expression is good enough to cover all nullish conditions and shorter than `creationTime == null`.

2023-01-11 16:52 UTC, szkl commented on platform/access/wrangler.toml
> +  { binding = "EDGES", service = "edges" },
`Edges`

2023-01-11 16:55 UTC, crimeminister commented
> It is not JSON-RPC anymore. I think the request body snippets in `curl` directory are useless now.

I'll remove them. Do we have any other examples in docs or files to demonstrate usage that we can replace them with?

2023-01-11 16:57 UTC, crimeminister commented on platform/access/wrangler.toml
> +  { binding = "EDGES", service = "edges" },
This has to match the binding name defined in the [platform middleware](https://github.com/kubelt/kubelt/blob/main/packages/platform-middleware/edges.ts#L5) or type errors occur.

2023-01-11 17:08 UTC, crimeminister commented on platform/access/src/nodes/access.ts
> +      expiry = new Date(expiryTime).toUTCString()
I try to avoid passing around integer timestamps outside of a service because they come with no context attached and are harder to interpret and debug, i.e. are we dealing with s, ms, ns? That's especially true when we're working on a system using stuff that has timestamps defined in seconds (JWT expiry, possibly others?). A UTC string doesn't seem to have these issues, being self-describing, easy to interpret, etc. That said, I'm not wedded to this format because it's not clear to me how this data will be used by the client; likely there will be some parsing and formatting required before displaying to the user.

2023-01-11 17:12 UTC, crimeminister commented on platform/access/src/jsonrpc/middleware/injectAccessNode.ts
> +export const InjectAccessNode: BaseMiddlewareFunction<Context> = async ({
There's an existing `InjectEdges` middleware I used as a model. Happy to rename, but we should maybe pick a convention and update everything in a new PR?

2023-01-11 17:15 UTC, crimeminister commented on platform/access/src/jsonrpc/middleware/injectAccessNode.ts
> +      ...ctx,
Fixed.

2023-01-11 17:17 UTC, crimeminister commented on platform/access/src/jsonrpc/middleware/injectAccessNode.ts
> +export const InjectAccessNode: BaseMiddlewareFunction<Context> = async ({
Oh, I think you're suggesting that we use this naming patter just for middleware that injects a DO proxy stub into the context, and not more generally for other things?

2023-01-11 17:22 UTC, crimeminister commented on platform/access/src/nodes/access.ts
> +  if (creationTime === undefined) {
Fixed!

2023-01-11 17:23 UTC, crimeminister commented on packages/platform-middleware/jwt.ts
> +  if (ctx?.accountURN === undefined) {
Is there a reason why `null` would be assigned to this value if has the initial value of `undefined`? Or is this more in the spirit of defensive programming?

2023-01-11 17:26 UTC, crimeminister commented on platform/access/src/context.ts
> +  edgesClient?: ReturnType<typeof createEdgesClient>
Not every route uses the middleware to inject the client, only the routes that require talking to that service do. Since the context is shared by all routes, the values that are only initialized for some routes I assume have to optional. Perhaps there's a more idiomatic way to deal with this in `tRPC`, or should we just use the `InjectEdges` middleware for all routes?

2023-01-11 17:27 UTC, crimeminister commented
> > It is not JSON-RPC anymore. I think the request body snippets in `curl` directory are useless now.
> 
> I'll remove them. Do we have any other examples in docs or files to demonstrate usage that we can replace them with?

Removed.

2023-01-11 17:35 UTC, crimeminister commented on platform/access/src/jsonrpc/middleware/injectAccessNode.ts
> +export const InjectAccessNode: BaseMiddlewareFunction<Context> = async ({
Renamed.

2023-01-11 18:53 UTC, szkl commented on platform/access/package.json
> +    "typed-json-rpc": "1.1.0",
Nope.

2023-01-11 18:53 UTC, szkl approved these changes

2023-01-12 15:29 UTC, merged