convert dapp to log with timbre
kubelt/kubelt pull request #292
Opened 2022-04-08 15:28 UTC by billkube

# Description

updating debug info to use timbre logging 

Closes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-08 16:24 UTC, drew-patel approved these changes
Beautiful. Thank you!

2022-04-08 18:15 UTC, crimeminister commented
Hey @billkube, you might want to use the `trace` or `debug` logging level for some of these logging calls, depending on how permanent they are. And for what it's worth, I usually like to log maps or objects as many logging systems, e.g. StackDriver will do useful things with logged data.

2022-04-08 19:17 UTC, drew-patel requested changes
Minor stuff. Feel free to push back if you feel it's too early to implement some of this stuff

2022-04-08 19:17 UTC, drew-patel commented on dapp/src/dapp/components/login.cljs
> +                  (log/debug {:provider "provider"})
This only shows the `"provider"` string. Did you want to replace this with just `provider` so we can see the object?

2022-04-08 19:17 UTC, drew-patel commented on dapp/src/dapp/components/login.cljs
> +                   (log/error error))))))
Let's follow the pattern that @crimeminister suggested. 

I'm even fond of something like
`{:error/message "some useful message" :error/stacktrace error}`

Not too particular about the names but happy to hear @crimeminister's thoughts

2022-04-08 19:17 UTC, drew-patel commented on dapp/src/dapp/pages/dashboard.cljs
> +  (log/trace "open the modal")
Wrap in hash-map? I think we can do an error template function and we can just use that everywhere for each type of error down the line. Don't have to do that now.

2022-04-08 19:17 UTC, drew-patel commented on dapp/src/dapp/wallet.cljs
> +          _ (log/debug {:msg "connect-account" :wallet wallet :web3 web3 :db db})
Delete `:db db` here? Maybe too much to log. Or just log the `:sdk/ctx` from the `db`?

2022-04-12 13:20 UTC, drew-patel approved these changes

2022-04-12 13:23 UTC, merged