doc(blog): hello kubelt
kubelt/kubelt pull request #303
Opened 2022-04-11 19:51 UTC by maurerbot

# Description

Our response to Moxie, Vitalik, and David Vorick (skynet)

## Type of change

- [x] Content / Docs

# How Has This Been Tested?

- [ ] localhost

# Checklist:

- [ ] My changes generate no new warnings

2022-04-13 19:04 UTC, crimeminister commented on www/content/en/blog/01-hello-world/moxie-vitalik-kubelt.md
> +Platforms acheive this value through focused, hyper opinionated services **in the middle** and, as confirmed by Moxie, this is a massive advantage for applications in early stages of development as l
```suggestion
Platforms achieve this value through focused, hyper-opinionated services **in the middle** and, as confirmed by Moxie, this is a massive advantage for applications in early stages of development as less resources are required to get to innovate. But what's the catch?
```

2022-04-13 19:05 UTC, crimeminister commented on www/content/en/blog/01-hello-world/moxie-vitalik-kubelt.md
> +Similar to the story of [The Walrus and the Carpenter](https://en.wikipedia.org/wiki/The_Walrus_and_the_Carpenter) all of this sounds great _until its not_. As your application scales with your succe
```suggestion
Similar to the story of [The Walrus and the Carpenter](https://en.wikipedia.org/wiki/The_Walrus_and_the_Carpenter) all of this sounds great _until it's not_. As your application scales with your success, the cost of these choices begin to show their fangs and you have little means of replatforming. Now you are stuck with the surprise compute and egress fees eating away at your bottom line and the pressure is on.
```

2022-04-13 19:10 UTC, crimeminister commented on www/content/en/blog/01-hello-world/moxie-vitalik-kubelt.md
> +Where we started thinking is, if blockchains are decentralized and clients are decenteralized, could we push all the opinions out to the user at the the edge?
```suggestion
Where we started thinking is, if blockchains are decentralized and clients are decentralized, could we push all the opinions out to the user at the the edge?
```

2022-04-13 19:14 UTC, crimeminister commented on www/content/en/blog/01-hello-world/moxie-vitalik-kubelt.md
> +If co-location of data and compute makes for a better developer experience and focused opinionted services accelerate development, how can we apply this in a dencentralized platform and get similar r
```suggestion
If co-location of data and compute makes for a better developer experience and focused opinionated services accelerate development, how can we apply this in a decentralized platform and get similar results without the trade offs?
```

2022-04-19 03:06 UTC, szkl requested changes
Typos.

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +In doing so, we should be able to co-locate everything with the user and take advantage of a local-first application model using user cryptography and ubiquitous runtimes. When the problem is **user
s/user/use/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +Starting from the early days of the Message Object Model (SmallTalk, Corba) and the more recent State Actor Model (Erlang, Akka) we finally realized, the answer we were looking for was right infront
s/infront/in front/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +For Kubelt, the wallet is the entry point into the network which, unlike other patforms, eliminates the need to install any new software or create new identities. Instead, we create a **"private core
s/cyrptography/cryptography/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +Kubelt isn't built just for Web3. A Kubelt Core is a fully genearlized backend that can breakdown data silos and simplify integrations all in a very user permissined and private way. For instance, wi
s/genearlized/generalized/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +Kubelt isn't built just for Web3. A Kubelt Core is a fully genearlized backend that can breakdown data silos and simplify integrations all in a very user permissined and private way. For instance, wi
s/permissined/permissioned/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +Kubelt isn't built just for Web3. A Kubelt Core is a fully genearlized backend that can breakdown data silos and simplify integrations all in a very user permissined and private way. For instance, wi
s/favorit/favorite/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +It doesn't stop their either. Kubelt developers and users can provision single or multi-signing Kubelt cores that can be laid out in a configurations that gate and or commericalize access to public o
s/their/there/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +It doesn't stop their either. Kubelt developers and users can provision single or multi-signing Kubelt cores that can be laid out in a configurations that gate and or commericalize access to public o
s/in a configurations/in configurations/

2022-04-19 03:06 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +It doesn't stop their either. Kubelt developers and users can provision single or multi-signing Kubelt cores that can be laid out in a configurations that gate and or commericalize access to public o
s/commericalize/commercialize/

2022-04-19 03:10 UTC, szkl requested changes
Typos.

2022-04-19 03:10 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +In summary, Moxie argues people will never run their own servers and we tend to agree. For the majoirty of users, the convenience of centralized services far outweigh any known or otherwise unknown t
```suggestion
In summary, Moxie argues people will never run their own servers and we tend to agree. For the majority of users, the convenience of centralized services far outweigh any known or otherwise unknown trade offs in data privacy.
```

2022-04-19 03:10 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +A major selling point of centralization is the convenience of data aggregration and co-location of compute. When data and compute are co-located developing applications becomes very straight forward
```suggestion
A major selling point of centralization is the convenience of data aggregation and co-location of compute. When data and compute are co-located developing applications becomes very straight forward (more on that later). The more abstract the relationship between data and compute, the easier it is to create secure applications.
```

2022-04-19 03:10 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +In doing so, we should be able to co-locate everything with the user and take advantage of a local-first application model using user cryptography and ubiquitous runtimes. When the problem is **user
```suggestion
In doing so, we should be able to co-locate everything with the user and take advantage of a local-first application model using user cryptography and ubiquitous runtimes. When the problem is **user sized**, developers can use their favorite tools and libraries, simplifying their stack while maintaining:
```

2022-04-19 03:10 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +Starting from the early days of the Message Object Model (SmallTalk, Corba) and the more recent State Actor Model (Erlang, Akka) we finally realized, the answer we were looking for was right infront
```suggestion
Starting from the early days of the Message Object Model (SmallTalk, Corba) and the more recent State Actor Model (Erlang, Akka) we finally realized, the answer we were looking for was right in front of us, **Wallets!** With crypto wallets, developers could have ubiquitous local-first access to:
```

2022-04-19 03:10 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +For Kubelt, the wallet is the entry point into the network which, unlike other patforms, eliminates the need to install any new software or create new identities. Instead, we create a **"private core
```suggestion
For Kubelt, the wallet is the entry point into the network which, unlike other patforms, eliminates the need to install any new software or create new identities. Instead, we create a **"private core"** that keeps your cryptography private but adds an always available API developers can access for content, messaging and more. And that's only the beginning of what cores can offer.
```

2022-04-19 03:10 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +Kubelt isn't built just for Web3. A Kubelt Core is a fully genearlized backend that can breakdown data silos and simplify integrations all in a very user permissined and private way. For instance, wi
```suggestion
Kubelt isn't built just for Web3. A Kubelt Core is a fully generalized backend that can breakdown data silos and simplify integrations all in a very user permissioned and private way. For instance, with Kubelt, your bank can generate content addresses containing your banking information using your favorite account software public key permissioned by you or host and permission your health care records, and more.
```

2022-04-19 03:10 UTC, szkl commented on www/content/en/blog/01-hello-world/index.md
> +It doesn't stop their either. Kubelt developers and users can provision single or multi-signing Kubelt cores that can be laid out in a configurations that gate and or commericalize access to public o
```suggestion
It doesn't stop there either. Kubelt developers and users can provision single or multi-signing Kubelt cores that can be laid out in configurations that gate and or commercialize access to public or protected content. These types of configurations are great for SaaS applications, DAOs, and more.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu reviewed
Typos + Rephrasings in some places.

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +**Platforms** and **protocols** are two very different categories. The former is generally built on the latter introducing opininated technologies and services. These platforms force developers to co
```suggestion
**Platforms** and **protocols** are two very different categories. The former is generally built on the latter, introducing opinionated technologies and services. These platforms force developers to conform applications to their opinions -- the more significant the conformance, the stickier the technology and risk of exploitation.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +A major selling point of centralization is the convenience of data aggregration and co-location of compute. When data and compute are co-located developing applications becomes very straight forward
```suggestion
A central selling point of centralization is the convenience of data aggregation and co-location of computing. When data and computing are co-located, developing applications becomes very straightforward (more on that later). The more abstract the relationship between data and computing, the easier it is to create secure applications.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +Platforms achieve this value through focused, hyper-opinionated services **in the middle** and, as confirmed by Moxie, this is a massive advantage for applications in early stages of development as l
```suggestion
Platforms achieve this value through focused, hyper-opinionated services **in the middle**. As confirmed by Moxie, this is a massive advantage for applications in the early stages of development as fewer resources are required to innovate. But what's the catch?
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +Similar to the story of [The Walrus and the Carpenter](https://en.wikipedia.org/wiki/The_Walrus_and_the_Carpenter) all of this sounds great _until it's not_. As your application scales with your succ
```suggestion
Similar to the story of [The Walrus and the Carpenter](https://en.wikipedia.org/wiki/The_Walrus_and_the_Carpenter), all of this sounds great _until it's not_. As your application scales with your success, the cost of these choices begins to show their fangs, and you have little means of re-platforming. Now you are stuck with the surprise compute and egress fees eating away at your bottom line, and the pressure is on.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +What you want is a system that allows developers to enjoy the benefits in the decentralized model without any of the operational overhead and contingency planning for hyperbolic growth.
```suggestion
What you want is a system that allows developers to enjoy the benefits of the decentralized model without any of the operational overhead and contingency planning for hyperbolic growth.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +If co-location of data and compute makes for a better developer experience and focused opinionated services accelerate development, how can we apply this in a decentralized platform and get similar r
```suggestion
Suppose co-location of data and compute makes for a better developer experience and focuses opinionated services to accelerate development. How can we apply this in a decentralized platform and get similar results without the trade-offs?
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +Blockchain seems like the obvious answer and we would agree this is true for many use cases involving **trusted state transitions**. DeFi, NFT, and other transactional use cases that require a consen
```suggestion
Blockchain seems like the obvious answer, and we agree this is true for many use cases involving **trusted state transitions**. Defi, NFT, and other transactional use cases that require a consensus on state make great sense for blockchains! For these cases, smart contracts and associated fees provide an acceptable cost in DX and UX for increased trust, security, and transparency. This cost for developers and users is not acceptable for everything else, like application logic, content, and **eventually consistent** use cases
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +It is, afterall, the eventually consistent use case that makes up the bulk of all applications. This is where the team at Kubelt did a lot of thinking about how to develop a **decentralized middle ti
```suggestion
It is, after all, the eventually consistent use case that makes up the bulk of all applications. This is where the team at Kubelt did much thinking about how to develop a **decentralized middle tier**.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +Where we started thinking is, if blockchains are decentralized and clients are decentralized, could we push all the opinions out to the user at the the edge?
```suggestion
We started thinking that if blockchains and clients are decentralized, could we push all the opinions out to the user at the edge?
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +In doing so, we should be able to co-locate everything with the user and take advantage of a local-first application model using user cryptography and ubiquitous runtimes. When the problem is **user
```suggestion
In doing so, we should be able to co-locate everything with the user and take advantage of a local-first application model using user cryptography and ubiquitous runtimes. When the problem is **user sized**, developers can use their favorite tools and libraries, simplifying their stack while maintaining:
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +However, all of this is easier said then done! So, we decided to take a look around and see if any work in this area has been attempted in the past? What we found was an evolution ready to pop!
```suggestion
However, all of this is easier said than done! So, we decided to look around and see if any work in this area has been attempted in the past? What we found was an evolution ready to pop!
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +Starting from the early days of the Message Object Model (SmallTalk, Corba) and the more recent State Actor Model (Erlang, Akka) we finally realized, the answer we were looking for was right infront
```suggestion
Starting from the early days of the Message Object Model (SmallTalk, Corba) and the more recent State Actor Model (Erlang, Akka), we finally realized the answer we were looking for was right in front of us, **Wallets**! With crypto wallets, developers could have ubiquitous local-first access to:
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +To truly decentralize an application you also need to decentralize the application content itself. As we already discussed, most blockchains aren't great for this, with the exception of [Filecoin](ip
```suggestion
To truly decentralize an application, you also need to decentralize the application content itself. As we already discussed, most blockchains aren't great for this, except for [Filecoin](ipns://filecoin.io/). You can't run a blockchain on the client, so a **peer-to-peer content delivery network** like [IPFS](ipns://ipfs.io/) is just as important.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +When backing IPFS with Filecoin all content is available through a decentralized network encoded as immutable **content addresses**. These addresses can pack anything from JSON documents to sqlite da
```suggestion
When backing IPFS with Filecoin, all content is available through a decentralized network encoded as immutable **content addresses**. These addresses can pack anything from JSON documents to SQLite databases, WASM, and more -- you pick! You are also breaking problems down to a size that a client can handle at the edge where you can now **"bring your own opinions."**
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +These same content addresses can also pack and fully encrypt signatures, schemas, versions and more collapsing APIs into a fully decentralized protocol simplifying the traditional three-tier applicat
```suggestion
These same content addresses can also pack and fully encrypt signatures, schemas, versions, and more, collapsing APIs into a fully decentralized protocol simplifying the traditional three-tier application architecture. This isn't to be underestimated. It pushes almost the entire application to the client, meaning developers can create **novel applications** and their own user experiences on a uniform, distributed API surface permissioned by the end-user.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +When combining capacity, availability and distribution (IPFS + Filecoin) with _wallets_ we can now talk about a fully genearlized protocol that both convenient and useful for application developement
```suggestion
When combining capacity, availability, and distribution (IPFS + Filecoin) with _wallets_, we can now discuss a fully generalized protocol that is convenient and useful for application development. This is because wallets are ubiquitous across multiple platforms. We can use them to ensure access to content and capabilities are correctly governed in a way that is at par or better than centralized services.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +For Kubelt, the wallet is the entry point into the network which, unlike other patforms, eliminates the need to install any new software or create new identities. Instead, we create a **"private core
```suggestion
For Kubelt, the wallet is the entry point into the network, which, unlike other platforms, eliminates the need to install any new software or create new identities. Instead, we form a **"private core"** that keeps your cryptography private but adds an always available API that developers can access for content, messaging, and more. And that's only the beginning of what cores can offer.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +Kubelt isn't built just for Web3. A Kubelt Core is a fully genearlized backend that can breakdown data silos and simplify integrations all in a very user permissined and private way. For instance, wi
```suggestion
Kubert isn't built just for Web3. A Kubelt Core is a fully generalized backend that can break down data silos and simplify integrations, all user permissioned and private. For instance, with Kubelt, your bank can generate content addresses containing your banking information using your favorite account software public key permissioned by you or host and permission your health care records.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +It doesn't stop their either. Kubelt developers and users can provision single or multi-signing Kubelt cores that can be laid out in a configurations that gate and or commericalize access to public o
```suggestion
It doesn't stop there either. Kubelt developers and users can provide single or multi-signing Kubelt cores that can be laid out in configurations that gate and or commercialize access to public or protected content. These configurations are significant for SaaS applications, DAOs, and more.
```

2022-04-19 09:17 UTC, Cosmin-Parvulescu commented on www/content/en/blog/01-hello-world/index.md
> +Kubelt is building a bigger, better, user centric web. If you like what we're doing and want to learn more follow us on [Twitter](https://twitter.com/kubelt) and join us on [Discord](https://discord.
```suggestion
Kubelt is building a more extensive, better, user-centric web. If you like what we're doing and want to learn more, follow us on [Twitter](https://twitter.com/kubelt) and join us on [Discord](https://discord.gg/UgwAsJf6C5).
```

2022-04-22 20:13 UTC, szkl commented
Resolve the conflicts, please.

2022-04-22 21:04 UTC, szkl approved these changes

2022-04-22 21:04 UTC, merged