core(test): make dev faster
kubelt/kubelt pull request #645
Opened 2022-08-02 23:26 UTC by maurerbot

# Description

Added a test config so tests run faster.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Windows 10

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-02 23:28 UTC, szkl requested changes

2022-08-02 23:28 UTC, szkl commented on 3iD/package.json
> +    "dotenv-run-script": "^0.2.0",
Fixed versions, please.

`npm config set save-exact true`

2022-08-03 07:42 UTC, Cosmin-Parvulescu approved these changes

2022-08-03 07:42 UTC, Cosmin-Parvulescu commented on .github/workflows/develop.yaml
> +  # test-3iD:
We keep this comment?

2022-08-03 11:41 UTC, merged